CREATE TABLE IF NOT EXISTS users (
    rowid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS php_cookies (
    rowid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    id_session VARCHAR(256) NOT NULL UNIQUE,
    data TEXT,
    extra TEXT,
    creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expiration DATETIME NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(rowid) ON DELETE CASCADE ON UPDATE CASCADE
);